# Generated by Django 6.0.6 on 2026-07-17 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of (quantity x price_at_purchase) across this booking's items, computed once at creation time. Not a property/annotation: it must survive unchanged even if TicketTier.price changes later, exactly like price_at_purchase on each BookingItem.",
                        max_digits=10,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="PROTECT rather than CASCADE: an event with confirmed bookings attached should not be deletable out from under them. Events are archived, not deleted, once they have any real activity — see apps.events.services.delete_event.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_at_purchase",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bookings.booking",
                    ),
                ),
                (
                    "ticket_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_items",
                        to="events.tickettier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Item",
                "verbose_name_plural": "Booking Items",
                "db_table": "booking_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'stripe', 'khalti', 'esewa'. Blank until a real payments app sets it.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Payment",
                "verbose_name_plural": "Booking Payments",
                "db_table": "booking_payments",
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="bookings_user_id_1eeb34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["event", "status"], name="bookings_event_i_0ec2ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingitem",
            index=models.Index(
                fields=["booking"], name="booking_ite_booking_b3bf99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingitem",
            index=models.Index(
                fields=["ticket_tier"], name="booking_ite_ticket__d72d42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingitem",
            constraint=models.UniqueConstraint(
                fields=("booking", "ticket_tier"), name="unique_tier_per_booking"
            ),
        ),
    ]
