# Generated by Django 6.0.6 on 2026-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_hold_expires_at_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
