services:
  - type: web
    name: karyakram-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: karyakram-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: karyakram-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: karyakram-redis
          property: connectionString

  - type: worker
    name: karyakram-celery-worker
    env: python
    buildCommand: "cd backend && pip install -r requirements/production.txt"
    startCommand: "cd backend && celery -A config worker -l info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: karyakram-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: karyakram-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: karyakram-redis
          property: connectionString

databases:
  - name: karyakram-db
    databaseName: karyakram
    user: karyakram_user
