# Generated by Django 6.0.6 on 2026-07-16 23:24

import apps.users.models
import apps.users.validators
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "User"), ("ORGANIZER", "Organizer")],
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Required. 3-30 characters. Letters, digits, dot, underscore, hyphen only.",
                        max_length=150,
                        unique=True,
                        validators=[apps.users.validators.validate_username_format],
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Organizer-only. Set True once an admin approves the organizer.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.users.models.generate_otp, max_length=6
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "db_table": "email_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("organization_description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "citizenship_number",
                    models.CharField(
                        max_length=255,
                        validators=[apps.users.validators.validate_citizenship_number],
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        max_length=255,
                        validators=[apps.users.validators.validate_pan_number],
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        max_length=255,
                        validators=[apps.users.validators.validate_bank_account_number],
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "citizenship_document",
                    models.FileField(
                        help_text="Citizenship certificate (image or PDF).",
                        upload_to="organizers/documents/citizenship/",
                        validators=[apps.users.validators.OrganizerDocumentValidator()],
                    ),
                ),
                (
                    "pan_document",
                    models.FileField(
                        help_text="PAN card (image or PDF).",
                        upload_to="organizers/documents/pan/",
                        validators=[apps.users.validators.OrganizerDocumentValidator()],
                    ),
                ),
                (
                    "approval_requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer Profile",
                "verbose_name_plural": "Organizer Profiles",
                "db_table": "organizer_profiles",
                "ordering": ["-approval_requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_email_verified"],
                name="users_is_acti_9c2147_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailotp",
            constraint=models.UniqueConstraint(
                fields=("user", "purpose"), name="unique_active_otp_per_purpose"
            ),
        ),
    ]
