# Generated by Django 6.0.6 on 2026-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bank_account_number_user_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
