# Generated by Django 6.0.6 on 2026-07-10 05:48

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='user',
            name='is_nepali_citizen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer')], default='user', max_length=20),
        ),
    ]
