# Generated by Django 6.0.6 on 2026-07-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('comedy', 'Comedy'), ('music', 'Music'), ('sports', 'Sports'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('theatre', 'Theatre'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=20)),
                ('banner_image', models.ImageField(upload_to='events/banners/')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Optional venue-wide cap, independent of per-ticket-type quantities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'db_table': 'event_gallery_images',
            },
        ),
    ]
