# Generated by Django 6.0.6 on 2026-07-16 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="users.organizerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(
                fields=["is_active"], name="event_categ_is_acti_7c1496_idx"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                help_text="PROTECT rather than CASCADE/SET_NULL: a category with live events attached should not be deletable out from under them.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.eventcategory",
            ),
        ),
        migrations.AddField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_tiers",
                to="events.event",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_status_8890b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["visibility", "status"], name="events_visibil_408f17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "status"], name="events_organiz_6a581a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_datetime"], name="events_start_d_2ddaa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city"], name="events_city_aa4e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="eventimage",
            index=models.Index(
                fields=["event", "display_order"], name="event_image_event_i_a42708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickettier",
            index=models.Index(
                fields=["event", "is_active"], name="ticket_tier_event_i_86152e_idx"
            ),
        ),
    ]
