# Generated by Django 6.0.6 on 2026-08-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_latitude_remove_event_longitude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventimage',
            name='event_image_event_i_a42708_idx',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
