# Generated by Django 6.0.6 on 2026-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(choices=[("ESEWA", "eSewa")], max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="ID returned from the payment gateway (eSewa refId)",
                max_length=255,
            ),
        ),
    ]
