# Generated by Django 6.0.6 on 2026-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_provider_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
