# Generated by Django 6.0.6 on 2026-08-04 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_booking_hold_expires_at_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendee_name", models.CharField(max_length=255)),
                ("attendee_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("CHECKED_IN", "Checked In"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="VALID",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code_payload",
                    models.TextField(
                        blank=True, help_text="Signed JWT for the QR code"
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="bookings.booking",
                    ),
                ),
                (
                    "booking_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="bookings.bookingitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
                "indexes": [
                    models.Index(fields=["status"], name="tickets_status_fbbf05_idx"),
                    models.Index(fields=["booking"], name="tickets_booking_98f7e3_idx"),
                    models.Index(
                        fields=["booking_item"], name="tickets_booking_c0789b_idx"
                    ),
                ],
            },
        ),
    ]
